[info]
id = "cargo-info"
git = "https://gitlab.com/imp/cargo-info"
unsupported = [
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "x86_64-sun-solaris",
    "powerpc64-unknown-linux-gnu",
    "powerpc64le-unknown-linux-gnu",
    "mips64-unknown-linux-muslabi64",
    "mips64el-unknown-linux-muslabi64"
]
bins = ["cargo-info"]

[target.all]
features = "rustls"
no-default-features = true
