[info]
id = "oha"
git = "https://github.com/hatoo/oha"
unsupported = [
    "x86_64-unknown-freebsd",
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "armv7-unknown-linux-musleabihf",
    "aarch64-pc-windows-msvc",
    "x86_64-unknown-netbsd",
    "x86_64-unknown-illumos",
    "x86_64-sun-solaris",
    "powerpc64-unknown-linux-gnu",
    "powerpc64le-unknown-linux-gnu",
    "mips64-unknown-linux-muslabi64",
    "mips64el-unknown-linux-muslabi64"
]
bins = ["oha"]

[target.all]
features = "rustls"
no-default-features = true
