[info]
id = "rtx-cli"
git = "https://github.com/jdxcode/rtx"
unsupported = [
#    "riscv64gc-unknown-linux-gnu",
#    "s390x-unknown-linux-gnu",
#    "x86_64-pc-windows-msvc",
#    "aarch64-pc-windows-msvc",
#    "x86_64-sun-solaris",
#    "powerpc64-unknown-linux-gnu",
#    "powerpc64le-unknown-linux-gnu",
#    "mips64-unknown-linux-gnuabi64",
#    "mips64-unknown-linux-muslabi64",
#    "mips64el-unknown-linux-gnuabi64",
#    "mips64el-unknown-linux-muslabi64"
]
bins = ["rtx"]

[target.all]
features = "openssl,openssl/vendored"
