[info]
id = "rustypaste-cli"
git = "https://github.com/orhun/rustypaste-cli"
unsupported = [
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "powerpc64-unknown-linux-gnu",
    "powerpc64le-unknown-linux-gnu",
    "mips64-unknown-linux-muslabi64",
    "mips64el-unknown-linux-muslabi64"
]
bins = ["rpaste"]
