name: Renovate Bot

on:
  push:
    branches: [main]
    paths: [.github/workflows/renovate.yml, .github/renovate.json]
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run Renovate
        type: boolean
        default: false
        required: true
  schedule:
    - cron: '0 10 * * 3' # 10 UTC on Weds

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  statuses: read

jobs:
  renovate-bot:
    runs-on: ubuntu-latest
    environment: renovate-bot
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.RENOVATE_BOT_APP_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f7fad228a053c69a98e24f8e4f6cf40db8f61e08 # v44.2.1
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: ${{ github.repository }}
          RENOVATE_DRY_RUN: ${{ inputs.dryRun }}
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_GIT_AUTHOR: ${{ secrets.RENOVATE_BOT_GIT_AUTHOR }}
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.app-token.outputs.token }}
