# Holds all actions that are needed for stable template so Renovate can check them.
name: Stable Tmpl Never Run

on:
  workflow_dispatch:

permissions: { }

jobs:
  hold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
      - uses: actions/cache@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: cargo-prebuilt/cargo-prebuilt-action@v5
      - uses: actions/upload-artifact@v4
      - uses: actions/download-artifact@v5
      - uses: ncipollo/release-action@v1
